project:
  type: website
  output-dir: docs

website:
  title: "Maria Spano"
  navbar:
    background: transparent 
    right:
      - text: Home
        href: index.qmd
      - text: Research
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: about me
        href: about.qmd
      - icon: book
        href: https://scholar.google.com/citations?user=TUO_ID
      - icon: globe
        href: https://www.researchgate.net/profile/Maria-Spano-2


format:
  html:
    includes:
      head: lightbox-head.html
    theme: lux
    css: styles.css
    #include-before-body: navbar.html
    toc: false
    page-layout: full


